language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - android-26
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew build

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
